language: python
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
rvm:
 - "3.8"
 - "3.8-dev"
 - "nightly"
before_install:
  - "pip3 install -r requirements.txt"
 after_deploy:
  - aws configure set aws_access_key_id $AWS_ACCESS_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ID
